# The name of the Docker Compose environment.
name: devtrio-build-task-app
services:
  # The UI services.
  ui:
    # The UI Docker image, hosted on GitHub.
    image: ghcr.io/devtrio/devtrio-build-task-app:latest
    ports:
      #Make the UI available on http://localhost:3000
      - "3000:3000"
      # Tell the UI how to find your Spring Boot app.

    environment:
      - BACKEND_HOST=host.docker.internal
      - BACKEND_PORT=8080


